### ISSUE TITLE
canonical html tag points to localhost

### ISSUE THREAD

**Issue by bamnet** [brzaik/brz4#1]
It looks like there are two references to localhost:4000 in the final site.

```html
<link rel="canonical" href="http://localhost:4000/">
<link type="application/atom+xml" rel="alternate" href="http://localhost:4000/feed.xml" title="Brian Zaik - Product Designer and Engineer" />
```

The canonical tag might be throwing off search engines [[ref](https://support.google.com/webmasters/answer/139066?hl=en#2)] for the new site.

**Comment by brzaik** [comment]
Fixed in latest deployment - thanks!
